[package]
name = "bigset"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "*"
num-integer = "*"
bumpalo = { version = "*", features = ["collections"] }
num-prime = "=0.4.4"
num-modular = "*"
