[package]
name = "howlite-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
cfgrammar = "=0.13.7"
lrlex = "=0.13.7"
lrpar = "=0.13.7"

[build-dependencies]
cfgrammar = "=0.13.7"
lrlex = "=0.13.7"
lrpar = "=0.13.7"

[[bin]]
name = "parse"
