[package]
name = "howlite"
version = "0.1.0"
edition = "2021"

[dependencies]
howlite-syntax = { path = "../howlite-syntax" }
howlite-typecheck = { path = "../howlite-typecheck" }
preseli = { path = "../preseli" }
sunstone = { path = "../sunstone" }
thiserror = "*"
hashbrown = "*"
# memchr = { version = "2" }

[dev-dependencies]
# used for stress-testing symbol table
rand = { version = "=0.8.5" }

[[bin]]
name = "hlt-typecheck"
